name: Setup Rasa on Azure

on:
  push:
    branches:
      - main  # Ajuste conforme necessário

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3
        
      - name: Configurar Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Atualizar o Sistema e Instalar Dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip git

      - name: Instalar Dependências do Projeto
        run: |
          pip3 install --no-cache-dir -r requirements.txt
          pip3 install rasa

      - name: Iniciar o Rasa em Segundo Plano
        run: |
          rasa run -m models --enable-api --cors "*" &  # Executa em background
          sleep 30  # Aguarda 10 segundos para garantir que o Rasa iniciou

      - name: Testar se o Rasa está rodando
        run: curl --retry 10 --retry-delay 5 --max-time 30 http://localhost:5005

      - name: Manter o job ativo
        run: tail -f /dev/null  
