name: Setup Rasa on Azure

on:
  push:
    branches:
      - main  # Ajuste conforme necessário

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3
        
      - name: Configurar Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Atualizar o Sistema e Instalar Dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip git

      - name: Instalar Dependências do Projeto
        run: |
          pip3 install --no-cache-dir -r requirements.txt
          pip3 install rasa

      # Login no Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy para o Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chatbot-rasa'  # Nome do Web App
          slot-name: 'Production'  # Nome do Slot (se for necessário)
